import { AiFillHeart } from 'react-icons/ai';

export const cardData = [
  {
    title_1: 'Hot Deal',
    title_2: 'Auction',
    sale: 'sale',
    img: 'https://images.unsplash.com/photo-1667489022797-ab608913feeb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHw5fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=800&q=60',
    id: '#B8/456567',
    status: 'Enoch Citizen',
    icon: <AiFillHeart />,
    like_count: '92',
    bid_status: 'highest bid',
    percent_off: '15% OFF',
    old_price: '$300',
    bid_rate: '260',
    auction_end: 'Auction ends in',
    deal_ends: 'flash deal ends in',
    end_time: 'Time: Time: time',
  },
  {
    title_1: 'Hot Deal',
    title_2: 'Auction',
    sale: 'sale',
    img: 'https://images.unsplash.com/photo-1553117854-1b456e458002?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGNvY2ElMjBjb2xhfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
    id: '#B8/456567',
    status: 'Enoch Citizen',
    icon: <AiFillHeart />,
    like_count: '67',
    bid_status: 'highest bid',
    percent_off: '15% OFF',
    old_price: '$300',
    bid_rate: '260',
    auction_end: 'Auction ends in',
    deal_ends: 'flash deal ends in',
    end_time: 'Time: Time: time',
  },
  {
    title_1: 'Hot Deal',
    title_2: 'Auction',
    sale: 'sale',
    img: 'https://images.unsplash.com/photo-1664575602276-acd073f104c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDF8MHxlZGl0b3JpYWwtZmVlZHwxMXx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60',
    id: '#B8/456567',
    status: 'Enoch Citizen',
    icon: <AiFillHeart />,
    like_count: '32',
    bid_status: 'highest bid',
    percent_off: '15% OFF',
    old_price: '$300',
    bid_rate: '260',
    auction_end: 'Auction ends in',
    deal_ends: 'flash deal ends in',
    end_time: 'Time: Time: time',
  },
];
