import Head from 'next/head';
import Image from 'next/image';
import MainCard from '../components/card/MainCard';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Enoch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <MainCard />
      </main>
    </div>
  );
}
